### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Cubxity** [InventivetalentDev/SpigetJavaClient#1]
There is random NullPointerException error while console is printing resources when i use search api

**Comment by InventivetalentDev** [comment]
Be more specific please. E.g. Code, Stack trace, ...

**Comment by Cubxity** [comment]
```
[11:51:38 WARN]: java.lang.NullPointerException
[11:51:38 WARN]: 	at tk.cubestudio.plugloader.PluginLoad.lambda$pGet$0(PluginLoad.java:44)
[11:51:38 WARN]: 	at org.inventivetalent.spiget.client.spiget.client.DefaultSortedRequest.lambda$getSorted$1(DefaultSortedRequest.java:28)
[11:51:38 WARN]: 	at org.inventivetalent.spiget.client.spiget.client.SpigetClient.lambda$getDirect$2(SpigetClient.java:53)
[11:51:38 WARN]: 	at org.inventivetalent.spiget.client.spiget.client.SpigetClient.execute(SpigetClient.java:45)
[11:51:38 WARN]: 	at org.inventivetalent.spiget.client.spiget.client.SpigetClient.getDirect(SpigetClient.java:49)
[11:51:38 WARN]: 	at org.inventivetalent.spiget.client.spiget.client.DefaultSortedRequest.getSorted(DefaultSortedRequest.java:26)
[11:51:38 WARN]: 	at tk.cubestudio.plugloader.PluginLoad.pGet(PluginLoad.java:40)
[11:51:38 WARN]: 	at tk.cubestudio.plugloader.PluginLoad.onCommand(PluginLoad.java:28)
[11:51:38 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:51:38 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:51:38 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[11:51:38 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[11:51:38 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[11:51:38 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[11:51:38 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[11:51:38 WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[11:51:38 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:51:38 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:51:38 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[11:51:38 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[11:51:38 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[11:51:38 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[11:51:38 WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

Here you go
